# Sequences and null model

N-grams never cross verses. Within-verse shuffles preserve lengths and multiplicities.

Computational logic is in `src/torah_cantillation/`. These notebooks inspect generated evidence, not live API responses.

In [1]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display, Markdown
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "pyproject.toml").exists())
SNAPSHOT = 'primary-20261013'
REPORT = ROOT / "reports" / SNAPSHOT
assert (REPORT / "summary.json").exists(), "Run fetch, build and analyze for this snapshot first."
summary = json.loads((REPORT / "summary.json").read_text())
display(Markdown("**PILOT ONLY**" if summary["pilot"] else "Validated full reference coverage"))
print("Snapshot:", summary["snapshot"])

Validated full reference coverage

Snapshot: primary-20261013

## Bigrams

In [2]:
values = json.loads((REPORT / "tables" / "bigrams.json").read_text())
frame = pd.DataFrame(values if isinstance(values, list) else [values])
print("Total rows:", len(frame))
display(frame.head(40))

Total rows: 369

,conditional_probability,count,edition_id,example_refs,n,representation,sequence
0,0.867726,4697,tanach,"[Genesis 1:1, Genesis 1:3, Genesis 1:4, Genesi...",2,literal,"[U+05A5, U+0596]"
1,0.867726,4697,tanach,"[Genesis 1:1, Genesis 1:3, Genesis 1:4, Genesi...",2,token_distinct,"[U+05A5, U+0596]"
2,0.451162,3321,tanach,"[Genesis 1:2, Genesis 1:4, Genesis 1:6, Genesi...",2,literal,"[U+05A3, U+0594]"
3,0.451223,3321,tanach,"[Genesis 1:2, Genesis 1:4, Genesis 1:6, Genesi...",2,token_distinct,"[U+05A3, U+0594]"
4,0.395279,2495,tanach,"[Genesis 1:4, Genesis 1:9, Genesis 1:11, Genes...",2,literal,"[U+0596, U+0591]"
5,0.395279,2495,tanach,"[Genesis 1:4, Genesis 1:9, Genesis 1:11, Genes...",2,token_distinct,"[U+0596, U+0591]"
6,0.999577,2362,tanach,"[Genesis 1:7, Genesis 1:9, Genesis 1:10, Genes...",2,literal,"[U+05A4, U+0599]"
7,0.999577,2362,tanach,"[Genesis 1:7, Genesis 1:9, Genesis 1:10, Genes...",2,token_distinct,"[U+05A4, U+0599]"
8,0.430175,2338,tanach,"[Genesis 1:2, Genesis 1:7, Genesis 1:9, Genesi...",2,literal,"[U+0594, U+0596]"
9,0.430175,2338,tanach,"[Genesis 1:2, Genesis 1:7, Genesis 1:9, Genesi...",2,token_distinct,"[U+0594, U+0596]"
10,0.427256,2135,tanach,"[Genesis 1:7, Genesis 1:9, Genesis 1:15, Genes...",2,literal,"[U+0599, U+05A3]"
11,0.502708,2135,tanach,"[Genesis 1:7, Genesis 1:9, Genesis 1:15, Genes...",2,token_distinct,"[U+0599, U+05A3]"
12,0.396438,1981,tanach,"[Genesis 1:2, Genesis 1:10, Genesis 1:11, Gene...",2,literal,"[U+0599, U+0594]"
13,0.466447,1981,tanach,"[Genesis 1:2, Genesis 1:10, Genesis 1:11, Gene...",2,token_distinct,"[U+0599, U+0594]"
14,0.306876,1937,tanach,"[Genesis 1:1, Genesis 1:2, Genesis 1:4, Genesi...",2,literal,"[U+0596, U+05A5]"
15,0.306876,1937,tanach,"[Genesis 1:1, Genesis 1:2, Genesis 1:4, Genesi...",2,token_distinct,"[U+0596, U+05A5]"
16,0.255536,1881,tanach,"[Genesis 1:1, Genesis 1:2, Genesis 1:3, Genesi...",2,literal,"[U+05A3, U+0591]"
17,0.255571,1881,tanach,"[Genesis 1:1, Genesis 1:2, Genesis 1:3, Genesi...",2,token_distinct,"[U+05A3, U+0591]"
18,0.297845,1880,tanach,"[Genesis 1:1, Genesis 1:2, Genesis 1:3, Genesi...",2,literal,"[U+0596, U+05A3]"
19,0.297845,1880,tanach,"[Genesis 1:1, Genesis 1:2, Genesis 1:3, Genesi...",2,token_distinct,"[U+0596, U+05A3]"
20,0.329899,1793,tanach,"[Genesis 1:4, Genesis 1:6, Genesis 1:10, Genes...",2,literal,"[U+0594, U+05A5]"
21,0.329899,1793,tanach,"[Genesis 1:4, Genesis 1:6, Genesis 1:10, Genes...",2,token_distinct,"[U+0594, U+05A5]"
22,0.635518,1367,tanach,"[Genesis 1:12, Genesis 1:25, Genesis 1:28, Gen...",2,literal,"[U+059B, U+05A5]"
23,0.635518,1367,tanach,"[Genesis 1:12, Genesis 1:25, Genesis 1:28, Gen...",2,token_distinct,"[U+059B, U+05A5]"
24,0.150931,1111,tanach,"[Genesis 1:9, Genesis 1:11, Genesis 1:22, Gene...",2,literal,"[U+05A3, U+0597]"
25,0.150951,1111,tanach,"[Genesis 1:9, Genesis 1:11, Genesis 1:22, Gene...",2,token_distinct,"[U+05A3, U+0597]"
26,0.211032,922,tanach,"[Genesis 1:1, Genesis 1:10, Genesis 1:12, Gene...",2,literal,"[U+0591, U+05A5]"
27,0.211032,922,tanach,"[Genesis 1:1, Genesis 1:10, Genesis 1:12, Gene...",2,token_distinct,"[U+0591, U+05A5]"
28,0.939220,819,tanach,"[Genesis 1:4, Genesis 1:12, Genesis 1:22, Gene...",2,literal,"[U+05A7, U+059B]"
29,0.939220,819,tanach,"[Genesis 1:4, Genesis 1:12, Genesis 1:22, Gene...",2,token_distinct,"[U+05A7, U+059B]"
30,0.162097,810,tanach,"[Genesis 1:2, Genesis 1:7, Genesis 1:9, Genesi...",2,literal,"[U+0599, U+0599]"
31,0.361692,778,tanach,"[Genesis 1:4, Genesis 1:17, Genesis 1:22, Gene...",2,literal,"[U+059B, U+0596]"
32,0.361692,778,tanach,"[Genesis 1:4, Genesis 1:17, Genesis 1:22, Gene...",2,token_distinct,"[U+059B, U+0596]"
33,0.500000,776,tanach,"[Genesis 1:9, Genesis 1:12, Genesis 1:21, Gene...",2,literal,"[U+05A8, U+059C]"
34,0.500000,776,tanach,"[Genesis 1:9, Genesis 1:12, Genesis 1:21, Gene...",2,token_distinct,"[U+05A8, U+059C]"
35,0.162051,708,tanach,"[Genesis 1:17, Genesis 2:6, Genesis 2:22, Gene...",2,literal,"[U+0591, U+0596]"
36,0.162051,708,tanach,"[Genesis 1:17, Genesis 2:6, Genesis 2:22, Gene...",2,token_distinct,"[U+0591, U+0596]"
37,0.154726,676,tanach,"[Genesis 1:2, Genesis 1:4, Genesis 1:6, Genesi...",2,literal,"[U+0591, U+05A3]"
38,0.154726,676,tanach,"[Genesis 1:2, Genesis 1:4, Genesis 1:6, Genesi...",2,token_distinct,"[U+0591, U+05A3]"
39,0.306468,597,tanach,"[Genesis 1:25, Genesis 1:26, Genesis 1:29, Gen...",2,literal,"[U+0597, U+0599]"

## Trigrams

In [3]:
values = json.loads((REPORT / "tables" / "trigrams.json").read_text())
frame = pd.DataFrame(values if isinstance(values, list) else [values])
print("Total rows:", len(frame))
display(frame.head(40))

Total rows: 1265

,conditional_probability,count,edition_id,example_refs,n,representation,sequence
0,0.978454,2089,tanach,"[Genesis 1:7, Genesis 1:9, Genesis 1:15, Genes...",3,literal,"[U+0599, U+05A3, U+0594]"
1,0.978454,2089,tanach,"[Genesis 1:7, Genesis 1:9, Genesis 1:15, Genes...",3,token_distinct,"[U+0599, U+05A3, U+0594]"
2,0.997340,1875,tanach,"[Genesis 1:1, Genesis 1:2, Genesis 1:3, Genesi...",3,literal,"[U+0596, U+05A3, U+0591]"
3,0.997340,1875,tanach,"[Genesis 1:1, Genesis 1:2, Genesis 1:3, Genesi...",3,token_distinct,"[U+0596, U+05A3, U+0591]"
4,0.945343,1695,tanach,"[Genesis 1:4, Genesis 1:6, Genesis 1:10, Genes...",3,literal,"[U+0594, U+05A5, U+0596]"
5,0.945343,1695,tanach,"[Genesis 1:4, Genesis 1:6, Genesis 1:10, Genes...",3,token_distinct,"[U+0594, U+05A5, U+0596]"
6,0.443541,1473,tanach,"[Genesis 1:2, Genesis 1:7, Genesis 1:9, Genesi...",3,literal,"[U+05A3, U+0594, U+0596]"
7,0.443541,1473,tanach,"[Genesis 1:2, Genesis 1:7, Genesis 1:9, Genesi...",3,token_distinct,"[U+05A3, U+0594, U+0596]"
8,0.443361,1409,tanach,"[Genesis 1:11, Genesis 1:12, Genesis 1:16, Gen...",3,literal,"[U+05A5, U+0596, U+0591]"
9,0.443361,1409,tanach,"[Genesis 1:11, Genesis 1:12, Genesis 1:16, Gen...",3,token_distinct,"[U+05A5, U+0596, U+0591]"
10,0.999268,1366,tanach,"[Genesis 1:12, Genesis 1:25, Genesis 1:28, Gen...",3,literal,"[U+059B, U+05A5, U+0596]"
11,0.999268,1366,tanach,"[Genesis 1:12, Genesis 1:25, Genesis 1:28, Gen...",3,token_distinct,"[U+059B, U+05A5, U+0596]"
12,0.550804,1301,tanach,"[Genesis 1:10, Genesis 1:11, Genesis 1:12, Gen...",3,token_distinct,"[U+05A4, U+0599, U+0594]"
13,0.459780,1086,tanach,"[Genesis 1:10, Genesis 1:11, Genesis 1:21, Gen...",3,literal,"[U+05A4, U+0599, U+0594]"
14,0.326709,1085,tanach,"[Genesis 1:4, Genesis 1:6, Genesis 1:16, Genes...",3,literal,"[U+05A3, U+0594, U+05A5]"
15,0.326709,1085,tanach,"[Genesis 1:4, Genesis 1:6, Genesis 1:16, Genes...",3,token_distinct,"[U+05A3, U+0594, U+05A5]"
16,0.417019,985,tanach,"[Genesis 1:9, Genesis 1:15, Genesis 1:16, Gene...",3,token_distinct,"[U+05A4, U+0599, U+05A3]"
17,0.280994,893,tanach,"[Genesis 1:1, Genesis 1:4, Genesis 1:27, Genes...",3,literal,"[U+05A5, U+0596, U+05A5]"
18,0.280994,893,tanach,"[Genesis 1:1, Genesis 1:4, Genesis 1:27, Genes...",3,token_distinct,"[U+05A5, U+0596, U+05A5]"
19,0.275645,876,tanach,"[Genesis 1:3, Genesis 1:6, Genesis 1:10, Genes...",3,literal,"[U+05A5, U+0596, U+05A3]"
20,0.275645,876,tanach,"[Genesis 1:3, Genesis 1:6, Genesis 1:10, Genes...",3,token_distinct,"[U+05A5, U+0596, U+05A3]"
21,0.354784,838,tanach,"[Genesis 1:15, Genesis 1:16, Genesis 1:28, Gen...",3,literal,"[U+05A4, U+0599, U+05A3]"
22,0.399798,792,tanach,"[Genesis 1:2, Genesis 1:22, Genesis 1:26, Gene...",3,literal,"[U+0599, U+0594, U+0596]"
23,0.399798,792,tanach,"[Genesis 1:2, Genesis 1:22, Genesis 1:26, Gene...",3,token_distinct,"[U+0599, U+0594, U+0596]"
24,0.845987,780,tanach,"[Genesis 1:1, Genesis 1:10, Genesis 1:12, Gene...",3,literal,"[U+0591, U+05A5, U+0596]"
25,0.845987,780,tanach,"[Genesis 1:1, Genesis 1:10, Genesis 1:12, Gene...",3,token_distinct,"[U+0591, U+05A5, U+0596]"
26,0.333165,660,tanach,"[Genesis 1:10, Genesis 1:11, Genesis 1:21, Gen...",3,literal,"[U+0599, U+0594, U+05A5]"
27,0.333165,660,tanach,"[Genesis 1:10, Genesis 1:11, Genesis 1:21, Gen...",3,token_distinct,"[U+0599, U+0594, U+05A5]"
28,0.362876,651,tanach,"[Genesis 1:9, Genesis 1:15, Genesis 1:21, Gene...",3,literal,"[U+0594, U+0596, U+0591]"
29,0.362876,651,tanach,"[Genesis 1:9, Genesis 1:15, Genesis 1:21, Gene...",3,token_distinct,"[U+0594, U+0596, U+0591]"
30,0.339465,609,tanach,"[Genesis 1:2, Genesis 1:7, Genesis 1:20, Genes...",3,literal,"[U+0594, U+0596, U+05A3]"
31,0.339465,609,tanach,"[Genesis 1:2, Genesis 1:7, Genesis 1:20, Genes...",3,token_distinct,"[U+0594, U+0596, U+05A3]"
32,0.297659,534,tanach,"[Genesis 1:2, Genesis 1:20, Genesis 1:22, Gene...",3,literal,"[U+0594, U+0596, U+05A5]"
33,0.297659,534,tanach,"[Genesis 1:2, Genesis 1:20, Genesis 1:22, Gene...",3,token_distinct,"[U+0594, U+0596, U+05A5]"
34,0.209106,519,tanach,"[Genesis 1:12, Genesis 1:25, Genesis 2:12, Gen...",3,literal,"[U+0596, U+0591, U+05A5]"
35,0.209106,519,tanach,"[Genesis 1:12, Genesis 1:25, Genesis 2:12, Gen...",3,token_distinct,"[U+0596, U+0591, U+05A5]"
36,0.997849,464,tanach,"[Genesis 1:7, Genesis 1:11, Genesis 1:22, Gene...",3,literal,"[U+0597, U+05A4, U+0599]"
37,0.997849,464,tanach,"[Genesis 1:7, Genesis 1:11, Genesis 1:22, Gene...",3,token_distinct,"[U+0597, U+05A4, U+0599]"
38,0.551893,452,tanach,"[Genesis 1:4, Genesis 1:22, Genesis 2:4, Genes...",3,literal,"[U+05A7, U+059B, U+0596]"
39,0.551893,452,tanach,"[Genesis 1:4, Genesis 1:22, Genesis 2:4, Genes...",3,token_distinct,"[U+05A7, U+059B, U+0596]"

## Transition Null

In [4]:
values = json.loads((REPORT / "tables" / "transition_null.json").read_text())
frame = pd.DataFrame(values if isinstance(values, list) else [values])
print("Total rows:", len(frame))
display(frame.head(40))

Total rows: 2

,edition_id,eligible_verses,null,null_mean_mi_bits,null_values_bits,observed_mi_bits,p_bonferroni_across_reported_tests,permutation_p_exploratory,permutations,representation,seed
0,tanach,4685,shuffle within each verse; preserve lengths an...,0.056166,"[0.055624688081342626, 0.05446765073175815, 0....",1.663539,0.02,0.01,99,literal,42
1,tanach,4685,shuffle within each verse; preserve lengths an...,0.057616,"[0.05742961884062466, 0.0575375029204792, 0.05...",1.695020,0.02,0.01,99,token_distinct,42

## Interpretation

Check denominators, exclusions and edition scope. A truncated notebook display is not the complete occurrence catalog. See `summary.json` for checksums and environment versions.

In [5]:
display(Markdown((REPORT / "findings.md").read_text()))

# Computed findings

Snapshot: `primary-20261013`. **Full selected reference coverage validated.**

Encoded accents U+0591-U+05AE; all_signs separately audits U+05BD and other signs

## Corpus inventory

- `tanach`: 5,846 verses; 80,742 lexical tokens; 64,234 encoded accent signs in 26 code points; 4,686 verses eligible for sequence analysis.
  Most frequent encoded accents: HEBREW ACCENT TIPEHA (11,290); HEBREW ACCENT MUNAH (9,462); HEBREW ACCENT MERKHA (9,120); HEBREW ACCENT ZAQEF QATAN (6,998); HEBREW ACCENT PASHTA (6,378).

## Sequential dependence

- `tanach` / `literal`: observed adjacent-mark mutual information 1.6635 bits; within-verse shuffle mean 0.0562 bits; exploratory p=0.01; Bonferroni-adjusted p=0.02 (99 shuffles).
- `tanach` / `token_distinct`: observed adjacent-mark mutual information 1.6950 bits; within-verse shuffle mean 0.0576 bits; exploratory p=0.01; Bonferroni-adjusted p=0.02 (99 shuffles).

## Predictability

Leave-one-book-out log losses are in `tables/model_evaluation.json`. Unigram and bigram baselines use add-one smoothing and a fixed 30-symbol Unicode alphabet. Repeated consonantal verse texts in held-out books are removed from training.

## Interpretation limits

- Counts describe the encoded source snapshot, not every manuscript or chanting tradition.
- Literal inventory includes text in unresolved readings; inspect quality flags before claiming lexical or linguistic counts.
- Repeated signs remain in the literal layer. Token-distinct collapse is a sensitivity representation, not a linguistic truth.
- Markup, bracketed readings, orphan accents, multiple distinct accents on a token, and nonstandard verse endings exclude verses from sequence/model analysis, not the raw audit.
- Clusters and high-surprise verses are exploratory, not inferred genres, textual errors, or historical explanations.
- The shuffle tests one explicit null model. Descriptive counts are a corpus census, not sample estimates.
- Edition comparison is unrun unless two editions were acquired; inspect its status table.
- Silluq candidates are audited separately and excluded from accent-codepoint sequences.

## Evidence

All tables are under `tables/`. `summary.json` records provenance, environment versions, code and table checksums. `rare_occurrences.json` lists every occurrence of an encoded accent with total frequency <=20 in an edition. The complete occurrence inventory, including common signs, is `data/processed/<snapshot>/marks.jsonl`.